name: CI/CD

on:
  push:
    branches:
      - master  # Changed from main to master
  pull_request:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
        
      - name: Setup Java 17
        uses: actions/setup-java@v4  # Updated to v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2  # Updated to v2
        with:
          flutter-version: '3.32.8'  # Fixed version number
          cache: true
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze
        
      - name: Run tests
        run: flutter test
        
      - name: Build APK
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: release-apk
<<<<<<< HEAD
          path: build/app/outputs/flutter-apk/app-release.apk
=======
          path: build/app/outputs/flutter-apk/app-release.apk
>>>>>>> 7a0953c2e72f0d23560645ffea7c603fe58fe47f
